# Generated by Django 4.2.3 on 2023-07-20 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_accountmodel_friends'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddFriend',
        ),
    ]
