# Generated by Django 4.2.3 on 2023-07-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_addfriend'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='live_in',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='work_at',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
