# Generated by Django 4.2.3 on 2023-07-22 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialApp', '0002_commentmodel_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likemodel',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to='socialApp.commentmodel'),
        ),
    ]
