# Generated by Django 4.2.3 on 2023-07-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialApp', '0003_alter_likemodel_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
